# Generated by Django 5.0.6 on 2024-07-03 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.AutoField(primary_key=True, serialize=False)),
                ('GameName', models.CharField(max_length=100)),
                ('Description', models.TextField(default='No description provided')),
                ('ReleaseDate', models.DateField(default=django.utils.timezone.now)),
                ('Genre', models.CharField(default='No Genre provided', max_length=50)),
                ('RentPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('IsFree', models.BooleanField(default=True)),
            ],
        ),
    ]
